export enum ActionTypes {
  SIGNIN = 'APP/SIGNIN',
  REGISTR = 'APP/REGISTR',
  SHOWMSG = 'APP/SHOWMSG',
  HIDEMSG = 'APP/HIDEMSG',
  LOGOUT = 'APP/LOGOUT',
  DISABLEDFIELD = 'APP/DISABLEDFIELD',
  ENABLEDFIELD = 'APP/ENABLEDFIELD',
  ONCHAGEREGFIELD = 'REG/ONCHAGEREGFIELD',
  ONCHAGEAUTHFIELD = 'AUTH/ONCHAGEAUTHFIELD',
  FILLUSERDATA = 'APP/FILLUSERDATA',
  GETACCOUNT = 'APP/GETACCOUNT',
  GETOPERATOIN = 'APP/GETOPERATOIN',
	PAYOPERATION = 'APP/PAYOPERATION',
	NEXTSTEP = 'ORDER/NEXTSTEP',
  PREVSTEP = 'ORDER/PREVSTEP',
  UPDATEPAYMENTDATA = 'PAYMENT/UPDATEPAYMENTDATA',
  UPDATEGRIDTDATA = 'PAYMENT/UPDATEGRIDTDATA'
}