export enum ActionTypes {
  SIGNIN = 'APP/SIGNIN',
  REGISTR = 'APP/REGISTR',
  SHOWMSG = 'APP/SHOWMSG',
  HIDEMSG = 'APP/HIDEMSG',
  LOGOUT = 'APP/LOGOUT',
  DISABLEDFIELD = 'APP/DISABLEDFIELD',
  ENABLEDFIELD = 'APP/ENABLEDFIELD',
  ONCHAGEREGFIELD = 'REG/ONCHAGEREGFIELD',
  ONCHAGEAUTHFIELD = 'AUTH/ONCHAGEAUTHFIELD',
  FILLUSERDATA = 'APP/FILLUSERDATA'
}